clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 1

    # The number of clients selected in each round
    per_round: 1

    # Should the clients compute test accuracy locally?
    do_test: true

server:
    address: localhost
    port: 8000

data:
    # The training and testing dataset
    dataset: COCO

    # Where the dataset is located
    data_path: ./data/COCO
    train_path: ./data/COCO/coco128/images/train2017/
    test_path: ./data/COCO/coco128/images/train2017/

    # download command/URL (optional)
    download_urls:
        [
            "https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip",
        ]

    # number of training examples
    num_train_examples: 128

    # number of testing examples
    num_test_examples: 128

    # number of classes
    num_classes: 80

    # image size
    image_size: 640

    # class names
    classes:
        [
            "person",
            "bicycle",
            "car",
            "motorcycle",
            "airplane",
            "bus",
            "train",
            "truck",
            "boat",
            "traffic light",
            "fire hydrant",
            "stop sign",
            "parking meter",
            "bench",
            "bird",
            "cat",
            "dog",
            "horse",
            "sheep",
            "cow",
            "elephant",
            "bear",
            "zebra",
            "giraffe",
            "backpack",
            "umbrella",
            "handbag",
            "tie",
            "suitcase",
            "frisbee",
            "skis",
            "snowboard",
            "sports ball",
            "kite",
            "baseball bat",
            "baseball glove",
            "skateboard",
            "surfboard",
            "tennis racket",
            "bottle",
            "wine glass",
            "cup",
            "fork",
            "knife",
            "spoon",
            "bowl",
            "banana",
            "apple",
            "sandwich",
            "orange",
            "broccoli",
            "carrot",
            "hot dog",
            "pizza",
            "donut",
            "cake",
            "chair",
            "couch",
            "potted plant",
            "bed",
            "dining table",
            "toilet",
            "tv",
            "laptop",
            "mouse",
            "remote",
            "keyboard",
            "cell phone",
            "microwave",
            "oven",
            "toaster",
            "sink",
            "refrigerator",
            "book",
            "clock",
            "vase",
            "scissors",
            "teddy bear",
            "hair drier",
            "toothbrush",
        ]

    # Number of samples in each partition
    partition_size: 128

    # IID, biased, or sharded?
    divider: sharded

    shard_per_client: 2

trainer:
    # The type of the trainer
    type: basic

    loss: yololoss

    # The maximum number of training rounds
    rounds: 100

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.99

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 4
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model: yolov5
    model_config: models/yolov5/yolov5s.yaml

algorithm:
    # Aggregation algorithm
    type: fedavg
