[project]
name = "fedunlearning"
version = "0.1.0"
description = "Federated Unlearning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.8",
    "scikit-learn>=1.7.2",
]
