clients:

    type: simple_ssl

    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 2

    # Should the clients compute test accuracy locally?
    do_test: true
    do_personalized_test: true

    # the ratio of clients participanting in training
    participant_clients_ratio: 0.5
    
    # whether maintain and load the trained 
    # personalied model
    # set to be true, each client will load
    # the latest trained personalized model
    persist_personalized_model: False

server:

    type: fedavg_personalized
    address: 127.0.0.1
    port: 8000

    do_test: false
    
    # do personalization 
    # for every `do_personalization_interval` rounds
    # set -1 to do personalized only after the final round
    do_personalization_interval: -1
    # total, participant, nonparticipant
    do_personalization_group: nonparticipant

data:
    # The training and testing dataset
    datasource: CIFAR10
    personalized_datasource: CIFAR10

    # Number of samples in each partition
    partition_size: 2000

    train_transform: SimCLR
    # test_transform: 
    # personalized_train_transform:
    # personalized_test_transform:

    # IID or non-IID?
    sampler: noniid
    testset_sampler: noniid

    # personalized_sampler: noniid
    # personalized_testset_sampler: noniid

    # The concentration parameter for the Dirichlet distribution
    concentration: 0.5

    # The random seed for sampling data
    random_seed: 1

trainer:

    type: basic_ssl

    # The maximum number of training rounds
    rounds: 1

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # The target accuracy
    target_accuracy: 0.94

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 32
    optimizer: SGD
    lr_scheduler: MultiStepLR
    loss_criterion: NegativeCosineSimilarity

    # Number of epochs for local training in each communication round
    #   The batch size for the downstream task can be larger as it
    # does not utilize the
    personalized_epochs: 5
    personalized_batch_size: 32
    personalized_optimizer: SGD
    personalized_lr_scheduler: StepLR
    personalized_loss_criterion: CrossEntropyLoss

    pers_epoch_log_interval: 2

    # The machine learning model
    model_name: BYOL
    encoder_name: resnet_18
    personalized_model_type: general_multilayer
    personalized_model_name: linear_mlp

    projection_hidden_dim: 1024
    projection_out_dim: 256
    prediction_hidden_dim: 1024
    prediction_out_dim: 256

    global_modules_name:
        - encoder
        - projection_head
        - prediction_head

algorithm:
    # Aggregation algorithm
    type: fedavg_partial

parameters:
    train_transform:
        # input_size
        #  - STL10 (Image size=96)
        #  - CIFAR10 (Image size=32)
        #  - MNIST (Image size=28)
        input_size: 32


    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0

    personalized_optimizer:
        lr: 0.01 # this is the alpha of the perfedavg paper
        momentum: 0.9
        weight_decay: 0.0

    learning_rate:
        gamma: 0.1
        milestone_steps: 150ep,350ep

    personalized_learning_rate:
        gamma: 0.3
        step_size: 10

    loss_criterion:
        eps: 1.0E-8
        
    personalized_loss_criterion:
        label_smoothing: 0.5

    model:
        num_classes: 10

    personalized_model:
        num_classes: 10

