#!/usr/bin/env python
"""
Test running a lot of selected configs.
This is for testing staleness bound.
"""

import subprocess
import time
import os

if __name__ == '__main__':
    for t in [
            'configs/port/stal_0',
            'configs/port/stal_1',
            'configs/port/stal_2',
            'configs/port/stal_3',
            'configs/port/stal_6',
            'configs/port/stal_9',
    ]:
        print(f"Running config: {t}.yml")
        subprocess.call(['./run', f'--config={t}.yml'])