#!/usr/bin/env python
"""
Test running a lot of selected configs.
This is for testing staleness bounds with min_5.
"""

import subprocess
import time
import os

if __name__ == '__main__':
    for t in [
            'configs/port/min_5_stal_1',
            'configs/port/min_5_stal_4',
            'configs/port/min_5_stal_7',
            'configs/port/min_5_stal_10',
            'configs/port/min_5_stal_13',
    ]:
        print(f"Running config: {t}.yml")
        subprocess.call(['./run', f'--config={t}.yml'])