#!/usr/bin/env python
"""
Test running a lot of selected configs.
"""

import subprocess
import time
import os

if __name__ == '__main__':
    for t in [
            'configs/port/min_1',
            'configs/port/min_5',
            'configs/port/min_10',
            'configs/port/min_15',
            'configs/port/sync',
    ]:
        print(f"Running config: {t}.yml")
        subprocess.call(['./run', f'--config={t}.yml'])
