clients:

    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 3

    # Should the clients compute test accuracy locally?
    do_test: true


server:
    address: 127.0.0.1
    port: 8005
    simulate_wall_time: false

    do_test: false
    
data:
    # The training and testing dataset
    datasource: CIFAR10

    # Number of samples in each partition
    partition_size: 5000

    # IID or non-IID?
    sampler: iid

    # The random seed for sampling data
    random_seed: 1

trainer:

    # The maximum number of training rounds
    rounds: 30

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 64
    optimizer: AdamW
    lr_scheduler: CosineAnnealingLR
    global_lr_scheduler: true

    # The machine learning model
    model_type: vit
    model_name: facebook@levit-128

    global_modules_name:
        - patch_embeddings
        - encoder

    personalized_modules_name:
        - classifier


algorithm:
    # Aggregation algorithm
    type: fedavg_partial


    completion_modules_name:
        - classifier

    personalization:

        # learning hyper-parameters for personalized learning
        epochs: 10
        batch_size: 32
        optimizer: SGD
        lr_scheduler: StepLR
        loss_criterion: CrossEntropyLoss

        model_type: vit
        model_name: facebook@levit-128

        frozen_modules_name:
            - features

        logging_iteration_interval: 50
        logging_epoch_interval: 1
        model_logging_epoch_interval: 2
        
        # the ratio of clients participanting in training
        participant_clients_ratio: 0.5
        
        # whether maintain and load the trained 
        # personalied model
        # set to be true, each client will load
        # the latest trained personalized model
        persist_personalized_model: False

        # do personalization 
        # for every `do_personalization_interval` rounds
        # set -1 to do personalized only after the final round
        do_personalization_interval: -1
        # total, participant, nonparticipant
        do_personalization_group: nonparticipant

parameters:
    model:
        num_labels: 10
        pretrained: false

    optimizer:
        lr: 0.00004
        weight_decay: 0.00000001

    learning_rate:
        eta_min: 0
        T_max: 30

    model:
        num_classes: 10

    personalized_model:
        num_classes: 10
