[project]
name = "AnyCostFL"
version = "0.1.0"
description = "Efficient On-Demand Federated Learning over Heterogeneous Edge Device"
requires-python = ">=3.13"
dependencies = [
    "plato-learn>=1.4.3",
    "einops>=0.8.2",
    "ptflops>=0.7.5"
]

[tool.uv.sources]
plato-learn = { workspace = true }
