clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 1

    # The number of clients selected in each round
    per_round: 1

    # Should the clients compute test accuracy locally?
    do_test: true

server:
    address: 127.0.0.1
    port: 8000

data: !include mnist_iid.yml

trainer:
    # Should MindSpore be used instead of PyTorch?
    use_mindspore: true

    # Should MindSpore be used with CPU as its target?
    cpuonly: true

    # The type of the trainer
    type: basic

    # The maximum number of training rounds in total
    rounds: 100

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.96

    # Parameters for local training in each communication round
    epochs: 2
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9

    # The machine learning model
    model_name: lenet5

algorithm:
    # Aggregation algorithm
    type: fedavg
