clients:
    # Type
    type: mpc

    # The total number of clients
    total_clients: 10

    # The number of clients selected in each round
    per_round: 3

    # Should the clients compute test accuracy locally?
    do_test: false

    # Processors for outbound data payloads
    outbound_processors:
        - mpc_model_encrypt_shamir

server:
    type: fedavg_mpc_shamir
    address: 127.0.0.1
    port: 8001
    random_seed: 1
    simulate_wall_time: true

    # Uncomment to use S3 storage (Need to start zookeeper at the following address and port before training)
    # # S3 bucket for communication between server and clients
    # s3_bucket: "fl-mpc"
    # s3_endpoint_url: "https://s3.us-east-1.amazonaws.com"

    # # Zookeeper for distributed lock, need to start zookeeper at the following address and port before training
    # zk_address: 127.0.0.1
    # zk_port: 2181

data: !include mnist_iid.yml

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 5

    # The maximum number of clients running concurrently
    max_concurrency: 5

    # The target accuracy
    target_accuracy: 0.985

    # The machine learning model
    model_name: lenet5

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 32
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    model:
        num_classes: 10

    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0