clients:
    # Type
    type: split_learning

    # The total number of clients
    total_clients: 1

    # The number of clients selected in each round
    per_round: 1

    # Should the clients compute test accuracy locally?
    do_test: false

    # Split learning iterations for each client
    iteration: 12500

server:
    type: split_learning
    random_seed: 1
    address: 127.0.0.1
    port: 8001

    # Server doesn't have to do test for every round in split learning
    do_test: false
    # model_path: /scratch/dixiyao/controlnet/models/plato/models
    # checkpoint_path: /scratch/dixiyao/controlnet/models/plato/checkpoints

data:
    # The training and testing dataset
    datasource: coco
    val_dataset: coco
    data_path: /scratch/dixiyao/
    condition: canny

    # Number of samples in each partition
    partition_size: 50000

    # Fixed random seed
    random_seed: 1

    # IID, biased, or sharded?
    sampler: iid

trainer:
    # The type of the trainer
    type: split_learning

    # The maximum number of training rounds
    rounds: 12500

    # The target accuracy
    target_accuracy: 0.95

    # The machine learning model
    model_name: controlnet

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 3
    optimizer: AdamW
    
algorithm:
    # Aggregation algorithm
    type: split_learning

    # Split learning flag
    split_learning: true

parameters:
    model:
        init_model_path: /scratch/dixiyao/controlnet/models/control_sd15_ini.ckpt
        model_structure: examples/controlnet_split_learning/OrgModel/cldm_v15
        safe: true
    optimizer:
        lr: 0.00001

results: 
    types: round, accuracy, elapsed_time, comm_overhead, server_time, client_time, server_mem, client_mem
