#!/usr/bin/env python
"""
Starting point for a Plato federated learning training session.
"""
import os
from plato.servers import registry as server_registry
import fednas_client
import fednas_ServerTrainer
import fednas_ClientTrainer
import fednas_server
import fednas_algorithm
from Darts.model_search import Network

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
os.environ["MKL_THREADING_LAYER"] = "GNU"
os.environ["TOKENIZERS_PARALLELISM"] = "false"


def main():
    """Starting point for a Plato federated learning training session."""
    client = fednas_client.Client(model=Network, algorithm=fednas_algorithm.ClientAlgorithm,
                                  trainer=fednas_ClientTrainer.Trainer)
    server = fednas_server.Server(model=Network, algorithm=fednas_algorithm.ServerAlgorithm,
                                  trainer=fednas_ServerTrainer.Trainer)

    server.run(client)


if __name__ == "__main__":
    main()
