clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 5

    # The number of clients selected in each round
    per_round: 3

    # Should the clients compute test accuracy locally?
    do_test: false

    # The round to remove the local data by clients
    data_deleted_round: 2

    # The percentage to remove the local data by clients
    delete_data_ratio: 0.3

server:
    address: 127.0.0.1
    port: 8000

    checkpoint_dir: ./models/fedun/mnist

data:
    # The training and testing dataset
    datasource: MNIST

    # Where the dataset is located
    data_path: ./data

    # Number of samples in each partition
    partition_size: 20000

    # IID or non-IID?
    sampler: iid

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 200

    # Whether the training should use multiple GPUs if available
    parallelized: true

    # The maximum number of clients running concurrently
    max_concurrency: 2

    # The target accuracy
    target_accuracy: 0.80

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 128
    #128,256,512,1024,2048
    optimizer: AdaHessian 
    learning_rate: 0.01
    momentum_b1: 0.9
    momentum_b2: 0.999
    create_graph: true
    eps: 1e-8
    weight_decay: 0.0
    hessian_power: 1.0

    # epochs: 1
    # batch_size: 128
    # optimizer: SGD
    # learning_rate: 0.001
    # momentum: 0.9
    # weight_decay: 0.0
    # # Learning rate schedule
    # lr_schedule: LambdaLR
    # lr_gamma: 0.1
    # lr_milestone_steps: 80ep,120ep

    # The machine learning model
    model_name: lenet5

algorithm:
    # Aggregation algorithm
    type: fedavg
