# The training and testing dataset
datasource: CIFAR10

# Number of samples in each partition
partition_size: 1024

# IID or non-IID?
sampler: noniid
testset_sampler: noniid
concentration: 1

# The random seed for sampling data
random_seed: 1
