clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 50

    # The number of clients selected in each round
    per_round: 20

server:
    address: 127.0.0.1
    port: 8000
    
    feddiv:
        warm_up_rounds: 5
        mixup: true

data:
    # The training and testing dataset
    datasource: CIFAR10

    # Number of samples in each partition
    partition_size: 4000

    # IID or non-IID?
    sampler: noniid
    # The random seed for sampling data
    random_seed: 1
    concentration: 0.5
    noise:
        # target accuracy for pre-trained model
        noise_accuracy: 0.6
        # type of pre-trained model
        noise_model: vgg_16
        # ratio of the wrong labels
        noise_ratio: 0.2
        #
        top_k: 5

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 150

    # The maximum number of clients running concurrently
    max_concurrency: 7

    # The target accuracy
    target_accuracy: 0.88

    # The machine learning model
    model_name: vgg_16

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 128
    optimizer: Adam

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    model:
        num_classes: 10

    optimizer:
        lr: 0.01
        weight_decay: 0.0
