clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 100

    # The number of clients selected in each round
    per_round: 40

    # Should the clients compute test accuracy locally?
    do_test: true

    random_seed: 1

server:
    address: 127.0.0.1
    port: 8000
    do_test: false
    random_seed: 1

    checkpoint_path: models/fedrep/cifar10
    model_path: models/fedrep/cifar10

data:
    # The training and testing dataset
    datasource: CIFAR10

    # Number of samples in each partition
    partition_size: 600

    # IID or non-IID?
    sampler: label_quantity_noniid
    per_client_classes_size: 2

    # The concentration parameter for the Dirichlet distribution
    concentration: 1

    testset_sampler: label_quantity_noniid

    # The random seed for sampling data
    random_seed: 1

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 100

    # The maximum number of clients running concurrently
    max_concurrency: 7

    # The target accuracy
    target_accuracy: 0.87

    # Number of epochs for local training in each communication round
    epochs: 10
    batch_size: 10
    optimizer: SGD
    learning_rate: 0.03
    momentum: 0.0 # learning rate is fixed as in Appendix C.2
    weight_decay: 0.0

    # Number of epoches for head optimization
    head_epochs: 9

    # The machine learning model
    model_name: resnet_18
    num_classes: 10

algorithm:
    # Aggregation algorithm
    type: fedavg
