general:
    base_path: .

clients:
    # Type
    type: simple

    # Should the clients compute test accuracy locally?
    do_test: false

    # Whether simulate clients or not
    speed_simulation: true

    # The simulation distribution
    simulation_distribution:
        distribution: pareto
        alpha: 1

    max_sleep_time: 80
    sleep_simulation: true
    avg_training_time: 20

    random_seed: 1

    # Reduction ratio of local epoch when erasing
    forget_local_epoch_ratio: 0.5

    # Retrain interval
    delta_t: 2
  
  #------------------- Need modification -------------------
    # The total number of clients
    total_clients: 250

    # The number of clients selected in each round
    per_round: 200
    # The round to remove the local data by clients
    # If do_optimized_clustering is true, it needs to add 2.
    # For example, if you want to do the data deletion after round 2
    # You should set it as round 4.
    data_deletion_round: 15

    # The clients which need to delete their local data samples
    clients_requesting_deletion: [35]

    # The percentage to delete the local data by clients
    deleted_data_ratio: 1

server:
    address: 127.0.0.1
    port: 8011
    do_test: true

    simulate_wall_time: true

    checkpoint_path: checkpoints/femnist/eraser
    model_path: models/femnist/eraser

    random_seed: 1

    # Should we run the FedEraser Algorithm?
    federaser: true
    
    # Should we operate in sychronous mode?
    synchronous: false
    # Should we do the cluster accuracy test during learning?
    do_clustered_test: true

    # Should be false. Specified in knot
    do_global_test: false

    staleness_bound: 1000

    #------------------- Need modification -------------------

    # The minimum arrival clients that all clusters can aggregrate
    minimum_clients_aggregated: 150

#=================== Only for clustering =================

# The window size that accuracy of each cluster should reach
#window_size: 3

#optimization clustering method; need to be comment when run fedun.py
#do_optimized_clustering: false

# The total number of clusters; need to be comment when run fedun.py
# clusters: 2

data:
    # The training and testing dataset
    datasource: FEMNIST

    sampler: all_inclusive

    concurrent_download: true
    
    reload_data: true
    
    partition_size: 1128
    
    # The random seed for sampling data
    random_seed: 1
    

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 40

    # The maximum number of clients running concurrently
    max_concurrency: 3

    # The target accuracy
    target_accuracy: 0.60

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0

    # Learning rate schedule
    lr_schedule: ExponentialLR
    lr_gamma: 0.99

    # The machine learning model
    model_name: lenet5
    num_classes: 62

#=================== Only for clustering =================
# The accuracy variance threshold that trigger the stop training sign
#target_accuracy_std: 0.02

algorithm:
    # Aggregation algorithm
    type: fedavg

results:
    types: round, accuracy, elapsed_time
    result_path: results/femnist/eraser
